fix for vm with no db client

diff --git a/git-dropbox b/git-dropbox
--- a/git-dropbox
+++ b/git-dropbox
@@ -1,11 +1,11 @@
 #!/bin/sh
 
-if [ ! -f ~/.dropbox/host.db ]; then
-	echo "dropbox database not found. install dropbox" >&2
-	exit 1
-fi
+# if [ ! -f ~/.dropbox/host.db ]; then
+# 	echo "dropbox database not found. install dropbox" >&2
+# 	exit 1
+# fi
 
-DROPBOX=$(awk 'FNR == 2' ~/.dropbox/host.db | openssl enc -a -d)
+DROPBOX="/Users/vmware/Dropbox"
 
 if [ ! -d "$DROPBOX" ]; then
 	echo "dropbox folder not found. install dropbox" >&2
